INCLUDE_PATH = 
SHELL = /bin/sh
CC = gcc
CPP = g++
CFLAGS = -O0 -pipe -fPIC -D_GNU_SOURCE -m64 -DEIF_THREADS -DEIF_LINUXTHREADS  -DEIF_IEEE_BEHAVIOR -DWORKBENCH -I"/home/affo/code/eiffel_playground/Eiffel/studio/spec/linux-x86-64/include" -I. $(INCLUDE_PATH)
CPPFLAGS = -O0 -pipe -fPIC -D_GNU_SOURCE -m64 -DEIF_THREADS -DEIF_LINUXTHREADS  -DWORKBENCH -I"/home/affo/code/eiffel_playground/Eiffel/studio/spec/linux-x86-64/include" -I. $(INCLUDE_PATH)
LDFLAGS = -m elf_x86_64
CCLDFLAGS = -m64  
LDSHAREDFLAGS =  -m elf_x86_64 -shared -o
EIFLIB = "/home/affo/code/eiffel_playground/Eiffel/studio/spec/linux-x86-64/lib/libmtwkbench.a"
EIFTEMPLATES = /home/affo/code/eiffel_playground/Eiffel/studio/config/linux-x86-64/templates
LIBS = -lm -lpthread
MAKE = make
AR = ar
LD = ld
MKDEP = \$(EIFFEL_SRC)/C/mkdep $(DPFLAGS) --
MV = /bin/mv
CP = /bin/cp
RANLIB = :
RM = /bin/rm -f
FILE_EXIST = 
RMDIR = 
X2C = "/home/affo/code/eiffel_playground/Eiffel/studio/spec/linux-x86-64/bin/x2c"
SHAREDLINK = ld
SHAREDLIBS = -lm
SHARED_SUFFIX = .so
COMMAND_MAKEFILE = 
START_TEST = if [ ! -f finished ] ; then 
END_TEST = ; fi 
CREATE_TEST = touch finished 
SYSTEM_IN_DYNAMIC_LIB = hilzer.so 

.SUFFIXES:.cpp .o

.c.o:
	$(CC) $(CFLAGS) -c $<

.cpp.o:
	$(CPP) $(CPPFLAGS) -c $<

OBJECTS = big_file_C1_c.o 

OLDOBJECTS =  ap866.o ap866d.o cu865.o cu865d.o ba864.o ba864d.o ca863.o ca863d.o \
	sh862.o sh862d.o so861.o so861d.o ti892.o ti892d.o c_867.o c_867d.o \
	da890.o da890d.o ti883.o ti883d.o ab884.o ab884d.o ti874.o ti874d.o \
	ti891.o ti891d.o da886.o da886d.o da875.o da875d.o da888.o da888d.o \
	fi889.o fi889d.o du880.o du880d.o ti873.o ti873d.o ti872.o ti872d.o \
	co879.o co879d.o ti871.o ti871d.o da882.o da882d.o da881.o da881d.o \
	da878.o da878d.o da885.o da885d.o da887.o da887d.o gr870.o gr870d.o \
	da869.o da869d.o da877.o da877d.o da876.o da876d.o da868.o da868d.o 

all: Cobj1.o

Cobj1.o: $(OBJECTS) Makefile
	$(LD) $(LDFLAGS) -r -o Cobj1.o $(OBJECTS)
	$(RM) $(OBJECTS)
	$(CREATE_TEST)

clean: local_clean
clobber: local_clobber

local_clean::
	$(RM) core finished *.o

local_clobber:: local_clean
	$(RM) Makefile

